# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pzhang/chen/density_flow

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pzhang/chen/density_flow

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pzhang/chen/density_flow/CMakeFiles /home/pzhang/chen/density_flow/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pzhang/chen/density_flow/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_sta

# Build rule for target.
test_sta: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_sta
.PHONY : test_sta

# fast build rule for target.
test_sta/fast:
	$(MAKE) -f CMakeFiles/test_sta.dir/build.make CMakeFiles/test_sta.dir/build
.PHONY : test_sta/fast

#=============================================================================
# Target rules for targets named test_cti

# Build rule for target.
test_cti: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_cti
.PHONY : test_cti

# fast build rule for target.
test_cti/fast:
	$(MAKE) -f CMakeFiles/test_cti.dir/build.make CMakeFiles/test_cti.dir/build
.PHONY : test_cti/fast

#=============================================================================
# Target rules for targets named test2

# Build rule for target.
test2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test2
.PHONY : test2

# fast build rule for target.
test2/fast:
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/build
.PHONY : test2/fast

#=============================================================================
# Target rules for targets named test1

# Build rule for target.
test1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test1
.PHONY : test1

# fast build rule for target.
test1/fast:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/build
.PHONY : test1/fast

#=============================================================================
# Target rules for targets named test_lbm

# Build rule for target.
test_lbm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_lbm
.PHONY : test_lbm

# fast build rule for target.
test_lbm/fast:
	$(MAKE) -f CMakeFiles/test_lbm.dir/build.make CMakeFiles/test_lbm.dir/build
.PHONY : test_lbm/fast

#=============================================================================
# Target rules for targets named test_porous_flow

# Build rule for target.
test_porous_flow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_porous_flow
.PHONY : test_porous_flow

# fast build rule for target.
test_porous_flow/fast:
	$(MAKE) -f CMakeFiles/test_porous_flow.dir/build.make CMakeFiles/test_porous_flow.dir/build
.PHONY : test_porous_flow/fast

test1.o: test1.cpp.o

.PHONY : test1.o

# target to build an object file
test1.cpp.o:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/test1.cpp.o
.PHONY : test1.cpp.o

test1.i: test1.cpp.i

.PHONY : test1.i

# target to preprocess a source file
test1.cpp.i:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/test1.cpp.i
.PHONY : test1.cpp.i

test1.s: test1.cpp.s

.PHONY : test1.s

# target to generate assembly for a file
test1.cpp.s:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/test1.cpp.s
.PHONY : test1.cpp.s

test2.o: test2.cpp.o

.PHONY : test2.o

# target to build an object file
test2.cpp.o:
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/test2.cpp.o
.PHONY : test2.cpp.o

test2.i: test2.cpp.i

.PHONY : test2.i

# target to preprocess a source file
test2.cpp.i:
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/test2.cpp.i
.PHONY : test2.cpp.i

test2.s: test2.cpp.s

.PHONY : test2.s

# target to generate assembly for a file
test2.cpp.s:
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/test2.cpp.s
.PHONY : test2.cpp.s

test_cti.o: test_cti.cpp.o

.PHONY : test_cti.o

# target to build an object file
test_cti.cpp.o:
	$(MAKE) -f CMakeFiles/test_cti.dir/build.make CMakeFiles/test_cti.dir/test_cti.cpp.o
.PHONY : test_cti.cpp.o

test_cti.i: test_cti.cpp.i

.PHONY : test_cti.i

# target to preprocess a source file
test_cti.cpp.i:
	$(MAKE) -f CMakeFiles/test_cti.dir/build.make CMakeFiles/test_cti.dir/test_cti.cpp.i
.PHONY : test_cti.cpp.i

test_cti.s: test_cti.cpp.s

.PHONY : test_cti.s

# target to generate assembly for a file
test_cti.cpp.s:
	$(MAKE) -f CMakeFiles/test_cti.dir/build.make CMakeFiles/test_cti.dir/test_cti.cpp.s
.PHONY : test_cti.cpp.s

test_lbm.o: test_lbm.cpp.o

.PHONY : test_lbm.o

# target to build an object file
test_lbm.cpp.o:
	$(MAKE) -f CMakeFiles/test_lbm.dir/build.make CMakeFiles/test_lbm.dir/test_lbm.cpp.o
.PHONY : test_lbm.cpp.o

test_lbm.i: test_lbm.cpp.i

.PHONY : test_lbm.i

# target to preprocess a source file
test_lbm.cpp.i:
	$(MAKE) -f CMakeFiles/test_lbm.dir/build.make CMakeFiles/test_lbm.dir/test_lbm.cpp.i
.PHONY : test_lbm.cpp.i

test_lbm.s: test_lbm.cpp.s

.PHONY : test_lbm.s

# target to generate assembly for a file
test_lbm.cpp.s:
	$(MAKE) -f CMakeFiles/test_lbm.dir/build.make CMakeFiles/test_lbm.dir/test_lbm.cpp.s
.PHONY : test_lbm.cpp.s

test_porous_flow.o: test_porous_flow.cpp.o

.PHONY : test_porous_flow.o

# target to build an object file
test_porous_flow.cpp.o:
	$(MAKE) -f CMakeFiles/test_porous_flow.dir/build.make CMakeFiles/test_porous_flow.dir/test_porous_flow.cpp.o
.PHONY : test_porous_flow.cpp.o

test_porous_flow.i: test_porous_flow.cpp.i

.PHONY : test_porous_flow.i

# target to preprocess a source file
test_porous_flow.cpp.i:
	$(MAKE) -f CMakeFiles/test_porous_flow.dir/build.make CMakeFiles/test_porous_flow.dir/test_porous_flow.cpp.i
.PHONY : test_porous_flow.cpp.i

test_porous_flow.s: test_porous_flow.cpp.s

.PHONY : test_porous_flow.s

# target to generate assembly for a file
test_porous_flow.cpp.s:
	$(MAKE) -f CMakeFiles/test_porous_flow.dir/build.make CMakeFiles/test_porous_flow.dir/test_porous_flow.cpp.s
.PHONY : test_porous_flow.cpp.s

test_sta.o: test_sta.cpp.o

.PHONY : test_sta.o

# target to build an object file
test_sta.cpp.o:
	$(MAKE) -f CMakeFiles/test_sta.dir/build.make CMakeFiles/test_sta.dir/test_sta.cpp.o
.PHONY : test_sta.cpp.o

test_sta.i: test_sta.cpp.i

.PHONY : test_sta.i

# target to preprocess a source file
test_sta.cpp.i:
	$(MAKE) -f CMakeFiles/test_sta.dir/build.make CMakeFiles/test_sta.dir/test_sta.cpp.i
.PHONY : test_sta.cpp.i

test_sta.s: test_sta.cpp.s

.PHONY : test_sta.s

# target to generate assembly for a file
test_sta.cpp.s:
	$(MAKE) -f CMakeFiles/test_sta.dir/build.make CMakeFiles/test_sta.dir/test_sta.cpp.s
.PHONY : test_sta.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... test_sta"
	@echo "... rebuild_cache"
	@echo "... test_cti"
	@echo "... test2"
	@echo "... test1"
	@echo "... test_lbm"
	@echo "... edit_cache"
	@echo "... test_porous_flow"
	@echo "... test1.o"
	@echo "... test1.i"
	@echo "... test1.s"
	@echo "... test2.o"
	@echo "... test2.i"
	@echo "... test2.s"
	@echo "... test_cti.o"
	@echo "... test_cti.i"
	@echo "... test_cti.s"
	@echo "... test_lbm.o"
	@echo "... test_lbm.i"
	@echo "... test_lbm.s"
	@echo "... test_porous_flow.o"
	@echo "... test_porous_flow.i"
	@echo "... test_porous_flow.s"
	@echo "... test_sta.o"
	@echo "... test_sta.i"
	@echo "... test_sta.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

